apiVersion: v1
kind: Pod
metadata:
  name: nginx-prod
spec:
  nodeSelector:
    env: prod
  containers:
    - name: nginx
      image: nginx:1.14.2


---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-dev
  labels:
    app: nginx_app
spec:
  nodeSelector:
    env: dev
  containers:
    - name: nginx-container
      image: nginx:latest