apiVersion: v1
kind: Pod
metadata:
  name: side-car-pod
spec:
  containers:
    - name: debug
      image: docker.io/rkalluru/learnk8s:side-car-html-generator
      volumeMounts:
        - mountPath: /mnt/html
          name: html
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
  volumes:
    - name: html
      emptyDir: {}