apiVersion: v1
kind: Pod
metadata:
  name: sidecar-demo
  labels:
    app: nginx
    env: dev
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: logs
          mountPath: /var/log/nginx
    - name: sidecar-logger
      image: busybox
      command: ['sh', '-c', 'tail -f /var/log/nginx/access.log']
      volumeMounts:
        - name: logs
          mountPath: /var/log/nginx
  volumes:
    - name: logs
      emptyDir: {}
