apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: storage-demo-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx

