apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"


---
apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
    - name: demo
      image: docker.io/rkalluru/learnk8s:rhel9-bare
      env:
        - name: DEMO_GREETING
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: player_initial_lives
        - name: DEMO
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: ui_properties_file_name

---
apiVersion: v1
kind: Pod
metadata:
  name: envfrom-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
    - name: demo
      image: docker.io/rkalluru/learnk8s:rhel9-bare
      envFrom:
        - configMapRef:
           name: game-demo
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service
data:
  - name: DB_HOST
    value: "wmp-dev.c4j048gm8kgc.us-east-1.rds.amazonaws.com"
  - name: DB_PORT
    value: "5432"
  - name: DB_USER
    value: "auth_svc_user"
  - name: DB_PASSWORD
    value: "localdev123"
  - name: DB_NAME
    value: "wmp"
  - name: DB_SCHEMA
    value: "auth_schema"
  - name: SERVER_PORT
    value: "8081"
  - name: JWT_SECRET
    value: "myDefaultSuperSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm"
  - name: PORTFOLIO_SERVICE_URL
    value: "http://portfolio-service-dev.devopsbymanju.shop:8080"

---
apiVersion: v1
kind: Pod
metadata:
  name: auth-service
spec:
  containers:
    - name: auth-service
      image: 200915316788.dkr.ecr.us-east-1.amazonaws.com/auth-service
      envFrom:
        - configMapRef:
            name: auth-service