apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    appName: nginx
spec:
  containers:
    - name: nginx
      image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cluster-ip
spec:
  selector:
    appName: nginx
  ports:
    - port: 80 # service port
      targetPort: 80  # nginx pod port
