apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    appName: nginx
spec:
  containers:
    - name: nginx
      image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: nginx_cluster_ip
spec:
  selector:
    appName: nginx
  ports:
    - port: 80
      targetPort: 80
