apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    appName: nginx
spec:
  containers:
    - name: nginx
      image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cluster-ip
spec:
  selector:
    appName: nginx
  ports:
    - port: 80 # service port
      targetPort: 80  # nginx pod port

---
apiVersion: v1
kind: Namespace
metadata:
  name: sample-namespace
---
# trying to access the nginx through service culster ip

apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  namespace: sample-namespace
spec:
  type: NodePort
  selector:
    appName: nginx
  ports:
    - port: 80 # service port
      targetPort: 80  # nginx pod port





