apiVersion: v1
kind: Pod
metadata:
  name: pod-tolerated-env
spec:
  containers:
    - name: nginx
      image: nginx
  tolerations:
    - key: "env"
      operator: "Equal"
      value: "dev"
      effect: "NoSchedule"

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-not-tolerated
spec:
  containers:
    - name: nginx
      image: nginx
#  tolerations:
#    - key: "project"
#      operator: "Equal"
#      value: "backend"
#      effect: "NoSchedule"
