apiVersion: v1
kind: Pod
metadata:
  name: nginx-required-during-schedule
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: env
                operator: In
                values:
                  - prod
  containers:
    - name: nginx
      image: nginx

