apiVersion: v1
kind: Pod
metadata:
  name: required-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: env
              operator: In
              values:
                - prod


