apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - catalogue
          topologyKey: "kubernetes.io/hostname"
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: pod
metadata:
  name: catalogue
  labels:
    app: catalogue
spec:
  containers:
    - name: nginx
      image: nginx:latest
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: nginx-dev
#  labels:
#    app: catalogue
#spec:
#  containers:
#    - name: nginx-container
#      image: nginx:latest