#apiVersion: v1
#kind: Pod
#metadata:
#  name: with-pod-affinity
#spec:
#  affinity:
#    podAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        - labelSelector:
#            matchExpressions:
#              - key: security
#                operator: In
#                values:
#                  - S1
#          topologyKey: topology.kubernetes.io/zone
#    podAntiAffinity:
#      preferredDuringSchedulingIgnoredDuringExecution:
#        - weight: 100
#          podAffinityTerm:
#            labelSelector:
#              matchExpressions:
#                - key: security
#                  operator: In
#                  values:
#                    - S2
#            topologyKey: topology.kubernetes.io/zone
#  containers:
#    - name: with-pod-affinity
#      image: registry.k8s.io/pause:3.8
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - catalogue
          topologyKey: "kubernetes.io/hostname"
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: pod
metadata:
  name: catalogue
  labels:
    app: catalogue
spec:
  containers:
    - name: nginx
      image: nginx:latest
