apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2026-02-22T06:20:33Z"
  name: gp3
parameters:
  fsType: xfs
  type: gp3
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  storageClassName: gp2
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: pod-pvc
#spec:
#  containers:
#    - name: myfrontend
#      image: nginx
#      volumeMounts:
#        - mountPath: "/opt"
#          name: claim1
#  volumes:
#    - name: claim1
#      persistentVolumeClaim:
#        claimName: claim1